version: '3.9'

services:
  db:
    image: postgres:latest
    container_name: db_postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - pgdata:/data/postgres

  migration:
    build: .
    container_name: transaction_migration
    depends_on:
      - db
    command: ['yarn', 'migration:run']
    env_file:
      - .env

volumes:
  pgdata:
    driver: local
